patterns:
  product:
    title: "Product Card"
    description: |
      This card can be used to display any product anywhere on the website.
    fields:
      - name: text
        type: string
        example: "Pretty Bracelet Name"
      - name: img
        type: string
        example: "bracelet-1.jpg"
      - name: url
        type: string
        example: "#"
