patterns:
  main-banner:
    title: "Main"
    description: |
      Use this banner on the home page of the website, it should always be the most important banner on the page.
    fields:
      - name: heading
        type: string
        example: "INDULGE IN LUXURY"
      - name: text
        type: string
        example: "Exquisite styles at affordable prices."
      - name: banner
        type: string
        example: "/images/banners/banner-2.jpg"
  secondary-banner:
    title: "Secondary"
    description: |
      This banner can be used on any page of the website, multiple can be used per page.
    fields:
      - name: heading
        type: string
        example: "SHOP THE COLLECTION"
      - name: text
        type: string
        example: "Beautiful and original pieces that make statements."
      - name: banner-l
        type: string
        example: "banner-l.jpg"
      - name: banner-m
        type: string
        example: "banner-m.jpg"
      - name: banner-s
        type: string
        example: "banner-s.jpg"
